export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FORM_FLUSH = "AUTH_FORM_FLUSH";
export const AUTH_AVATAR_CHANGE = "AUTH_AVATAR_CHANGE";
export const AUTH_PROFILE_UPDATE = "AUTH_PROFILE_UPDATE";
export const AUTH_RESET_PROFILE_UPDATED = "AUTH_RESET_PROFILE_UPDATED";

export const LANG_INIT = "LANG_INIT";
export const LANG_CHANGE = "LANG_CHANGE";
export const LANG_CHANGE_BY_ID = "LANG_CHANGE_BY_ID";
